# Generated by Django 4.2.30 on 2026-04-20 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task2", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Error",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.IntegerField(unique=True)),
                ("en", models.CharField(max_length=100)),
                ("ru", models.CharField(max_length=100)),
                ("uz", models.CharField(max_length=100)),
            ],
        ),
    ]
