# Generated by Django 4.2.30 on 2026-04-20 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_alter_card_options_alter_card_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='tg_id',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='card',
            name='phone',
            field=models.CharField(db_index=True, default=998990000000, max_length=13, unique=True),
            preserve_default=False,
        ),
    ]
