<<<<<<< HEAD
# Generated by Django 4.2.30 on 2026-06-10 10:45
=======
# Generated by Django 4.2.30 on 2026-06-22 10:51
>>>>>>> eaaa83ec9ab036be6f8c5f4b0befd22a76a2ec70

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_card_encryption'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'ordering': ['card_number_hash']},
        ),
    ]
