# Generated by Django 4.2.30 on 2026-06-22 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_card_encryption'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'ordering': ['card_number_hash']},
        ),
    ]
